#!/usr/bin/env ruby

git_bundles = [ 
  "https://github.com/astashov/vim-ruby-debugger.git",
  "https://github.com/ervandew/supertab.git",
  "https://github.com/godlygeek/tabular.git",
  "https://github.com/hallison/vim-rdoc.git",
  "https://github.com/msanders/snipmate.vim.git",
  "https://github.com/pangloss/vim-javascript.git",
  "https://github.com/scrooloose/nerdtree.git",
  "https://github.com/timcharper/textile.vim.git",
  "https://github.com/tpope/vim-cucumber.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/tpope/vim-git.git",
  "https://github.com/tpope/vim-haml.git",
  "https://github.com/tpope/vim-markdown.git",
  "https://github.com/tpope/vim-rails.git",
  "https://github.com/tpope/vim-repeat.git",
  "https://github.com/tpope/vim-surround.git",
  "https://github.com/tpope/vim-vividchalk.git",
  "https://github.com/tsaleh/taskpaper.vim.git",
  "https://github.com/tsaleh/vim-matchit.git",
  "https://github.com/tsaleh/vim-shoulda.git",
  "https://github.com/tsaleh/vim-tcomment.git",
  "https://github.com/tsaleh/vim-tmux.git",
  "https://github.com/vim-ruby/vim-ruby.git",
  "https://github.com/vim-scripts/Gist.vim.git",
  "https://github.com/scrooloose/syntastic",
  "https://github.com/rodjek/vim-puppet.git",
  "https://github.com/vim-scripts/Specky.git"
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
